name: leaderboard_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0-288.0.dev

dependencies:
  flutter:
    sdk: flutter
  flutter_highlight: ^0.7.0
  pie_chart: ^5.4.0
  pixelarticons: ^0.4.0
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: AlumniSans
      fonts:
        - asset: fonts/AlumniSans-VariableFont_wght.ttf
        - asset: fonts/AlumniSans-Italic-VariableFont_wght.ttf