name: leaderboard_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0-288.0.dev

dependencies:
  flutter:
    sdk: flutter
  flutter_highlight: ^0.7.0
  pie_chart: ^5.4.0
  pixelarticons: ^0.4.0
  provider: ^6.1.5
  dio: ^5.6.0
  retrofit: ^4.4.1
  json_annotation: ^4.9.0
  go_router: ^14.2.7
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0
  socket_io_client: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  retrofit_generator: ^9.1.5
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: AlumniSans
      fonts:
        - asset: fonts/AlumniSans-VariableFont_wght.ttf
        - asset: fonts/AlumniSans-Italic-VariableFont_wght.ttf